### ISSUE TITLE
Write original image reference to annotation.

### ISSUE THREAD

**Issue by brackendawson** [IBM/portieris#114]
As portieris mutates image references in pod specs to replace tags with digests, it could be helpful to users reading and coding against pod specs if it added an annotation with the original name, for example:

```
metadata:
  annotations:
    some.domain/images: icr.io/image:latest@sha256:cc292b92ce7f10f2e4f727ecdf4b12528127c51b6ddf6058e213674603190d06; icr.io/image:build57@sha256:5bb21ac469b5e7df4e17899d4aae0adfb430f0f0b336a2242ef1a22d25bd2e53
spec:
  containers:
  - name: container1
    image: icr.io/image@sha256:cc292b92ce7f10f2e4f727ecdf4b12528127c51b6ddf6058e213674603190d06
  - name: container2
    image: icr.io/image@sha256:5bb21ac469b5e7df4e17899d4aae0adfb430f0f0b336a2242ef1a22d25bd2e53
```
The domain to use in the key is an open question, if it is to be an API then apparently there **must** be one: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/

The full reference containing the tag and digest could be a suitable form for the value.

**Comment by sjhx** [comment]
propose to use `portieris.cloud.ibm.com` as the domain for this and for V1 image policy crds
would it be better to have an annotation per image e.g. domain/container 
hard to disagree with the use of repo:tag@digest in this case

**Comment by molepigeon** [comment]
I think it would be useful to have the image name as it was specified when the spec was created (ie with no mutations) in an annotation, so that operators or automation can refer to it later. We could have both, since the initial proposal would allow you to see which mutated digest corresponds to which requested tag.

**Comment by brackendawson** [comment]
We do have to put the annotation on the pod, there's no annotations on containers.

I would like to consider whether there is ever a possible case where one tag reference in multiple containers can be mutated to different digest references? I think it is possible now if a tag is replaced in the registry during processing. Without portieris in place it may already be possible as imagePullPolicy is set on the container. So we need to consider whether we include the container name (container ID is not possible) in this annotation. I would prefer not to.

As much as I like using the explicit tag and digest reference from the docker library implicitly as a mapping, I also would like the ability to lookup in this annotation without mutating my input, as @molepigeon has suggested.

I would propose that under this issue we:
1. Ensure that when portieris encounters a teg reference for an n<sup>th</sup> time it mutates it to the same digest. Use a cache which is valid for the current CRD.
2. Implement the following annotation:
```yaml
metadata:
  annotations:
    portieris.cloud.ibm.com/images: '{"icr.io/image:latest":"sha256:cc292b92ce7f10f2e4f727ecdf4b12528127c51b6ddf6058e213674603190d06","icr.io/image:build57":"sha256:5bb21ac469b5e7df4e17899d4aae0adfb430f0f0b336a2242ef1a22d25bd2e53"}'
spec:
  containers:
  - name: container1
    image: icr.io/image@sha256:cc292b92ce7f10f2e4f727ecdf4b12528127c51b6ddf6058e213674603190d06
  - name: container2
    image: icr.io/image@sha256:5bb21ac469b5e7df4e17899d4aae0adfb430f0f0b336a2242ef1a22d25bd2e53
```
There is precedent for using JSON blobs in annotations (sidecar.istio.io/status).

**Comment by sjhx** [comment]
I agree that the annotation cannot be added to the container but I was suggesting having a per container annotation named like `portieris.cloud.ibm.com/container1`. In which case the value of the annotation could be the image reference before mutation and need not include the digest, and does not need to be structured data and is more consumable.
I am not convinced that covering the corner case of retagging during deployment meets any complexity/utiltity tradeoff discussion, I prefer to keep the processing atomic.

**Comment by brackendawson** [comment]
We could do that, we'd want to add something else to the key or we would never be able to make another annotation, like:
```yaml
metadata:
  annotations:
    portieris.cloud.ibm.com/image/container1: "icr.io/image:latest"
    portieris.cloud.ibm.com/image/container2: "icr.io/image:build57"
spec:
  containers:
  - name: container1
    image: icr.io/image@sha256:cc292b92ce7f10f2e4f727ecdf4b12528127c51b6ddf6058e213674603190d06
  - name: container2
    image: icr.io/image@sha256:5bb21ac469b5e7df4e17899d4aae0adfb430f0f0b336a2242ef1a22d25bd2e53
```
