### ISSUE TITLE
Images not getting verified using policies defined in ImagePolicy

### ISSUE THREAD

**Issue by SrivigneshM** [IBM/portieris#136]
**Problem**
Neither ImagePolicy nor ClusterImagePolicy seems to be honored while installing kubernetes pod.

**What commit ID of Portieris did you experience the problem with?**
8a5adaf11b748b56d3f435fb9f79d2c3aa82a109

**What went wrong?**
Installed Portieris 0.6.0 using helm v3.1.2. Created custom image policy yaml and applied using kubectl apply -f allow-custom.yaml
Tried installing a kubernetes pod with image matching the repository name given in allow-custom.yaml. Image is pulled without any issues, but expected signature verification failure

**What should have happened differently?**
Signature verification should have happened with the notary server given in allow-custom.yaml policy 

**How can it be reproduced?**
1. Install helm v3.1.2
2. Install portieris 0.6.0
3. Create custom image policy yaml file given in below section
4. kubectl apply -f allow-custom.yaml
5. Create new kubernetes pod with image matching the repo name given in allow-custom.yaml

**Any other relevant information**
allow-custom.yaml

```
apiVersion: securityenforcement.admission.cloud.ibm.com/v1beta1
kind: ImagePolicy
metadata:
  name: allow-custom
spec:
   repositories:
    - name: "*"
      policy:
        trust:
          enabled: true
          trustServer: "https://notary.abc.com:4443"

```
kube-apiserver.yaml

`    - --enable-admission-plugins=NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,DefaultTolerationSeconds,MutatingAdmissionWebhook,ValidatingAdmissionWebhook
`
