### ISSUE TITLE
add ability to configure host mappings

### ISSUE THREAD

**Issue by causalityloop** [IBM/portieris#155]
In environments where network connectivity is limited, it would be helpful to allow users to configure DNS mappings (a.k.a /etc/hosts) to allow use of fully qualified names.

In a deployment yaml, specifically:
```
hostAliases:
- ip: "1.2.3.4"
  hostnames:
  - "acme.signcompany.local"
```
Since, deployment is done via helm, the above would need to be template friendly and configurable via values.yaml

**Comment by sjhx** [comment]
I assume this would be to support the use of a self hosted registry? I don't see a downside in allowing this default empty/off option.

**Comment by causalityloop** [comment]
That is correct. This would be to use a self hosted registry

**Comment by sjhx** [comment]
The intent of the PR is that a deployment command like
`helm install -n portieris --create-namespace portieris --values hosts.yaml`

Where hosts.yaml is 
```yaml
hostAliases:
- ip: "127.0.0.1"
  hostnames:
  - "foo.local"
  - "bar.local"
- ip: "10.1.2.3"
  hostnames:
  - "foo.remote"
  - "bar.remote"
```

Will set /etc/hosts in the portieris containers. 

Does this resolve the issue?
