### ISSUE TITLE
Resources with Customer Resource Definition Owner References are skipped

### ISSUE THREAD

**Issue by wmlynch** [IBM/portieris#246]
### What commit ID of Portieris did you experience the problem with?
portieris:v0.10.0
### What went wrong?
A daemonset resource with the following OwnerReference was not evaluated by portieris
```
    ownerReferences:
    - apiVersion: operator.tigera.io/v1
      blockOwnerDeletion: true
      controller: true
      kind: Installation
      name: default
```

### What should have happened differently?

The resource should have been evaluated
