### ISSUE TITLE
Do you have plan to support AWS ECR and google cloud container-registry

### ISSUE THREAD

**Issue by yuelipku** [IBM/portieris#26]
Hope to get some update on your plan of registry support.

**Comment by liamawhite** [comment]
@yuelipku Sorry for the delayed response!

I don't think either of these registries run Notary alongside them, am I wrong in that assertion? Would you be hosting your images their and running your own Notary instance?

**Comment by yuelipku** [comment]
Sorry, my mistake, I think you are right. I just need to run my own Notary instance there.

**Comment by jw-s** [comment]
@liamawhite I would also be interested in this #22 . I am more than happy to implement this. Do you have ideas in mind on how you want to tackle this? If not I can draft up something?

**Comment by liamawhite** [comment]
Great! I have been meaning to get around doing this actually so can help you along.

I think just a field in the CRD would be good. I guess at the spec level to prevent people from duplicating per repo. Something like this:

```
apiVersion: securityenforcement.admission.cloud.ibm.com/v1beta1
kind: <ClusterImagePolicy_or_ImagePolicy>
metadata:
  name: <crd_name>
spec:
   trustServer: <notary_server_url> # if not set it will infer based on image name
   repositories:
    - name: <repository_name>
      policy:
        trust:
          enabled: <true_or_false>
          signerSecrets:
          - name: <secret_name>
```
