### ISSUE TITLE
could not get porteiris to block any images

### ISSUE THREAD

**Issue by wu105** [IBM/portieris#40]
### What commit ID of Portieris did you experience the problem with?
recent master, commit 46e9cd5ef06f98853ae3674a3f023108eeafad53

### What went wrong?
deployed in the following environment:
kubernetes v1.9.1
helm v2.11
harbor v1.6.0 which provides registry and notary in question

1. command 'helm install -n portieris helm/portieris' would fail to deploy porteiris because namespace ibm-system does not exist.  It is very difficult to delete the failed helm release for re-install -- may need to keep deleting the failed jobs (due to missing namespace or service account) before helm delete times out.  The installation document may want to add a step to create namespace ibm-system and how to delete a failed porteiris release.

2. under the default clusterimagepolicy, unsigned images from the registry of our harbor installation should be blocked but they are not.  The test pod runs in the default namespace.  Adding a ImagePolicy below does not help;

```apiVersion: securityenforcement.admission.cloud.ibm.com/v1beta1
kind: ImagePolicy
metadata:
  name: test-image-policy
  namespace: default
spec:
  repositories:
  - name: '*'
    policy:
      trust:
        enabled: true
```
Adding `trustServer: https://notary.harbor.XYZ.com` to the above polilcy did not help either, where https://notary.harbor.XYZ.com is the notary url tested.  The registry url is https://core.harbor.XYZ.com

### What should have happened differently?
unsigned images should be blocked per image policy

### How can it be reproduced?
follow the description above, push some unsigned images into the registry, run a pod using the unsigned images in the default namespace.

### Any other relevant information
Would appreciate trouble shooting instructions.

**Comment by molepigeon** [comment]
Hi - thanks for your report. I've spun out your installation issues into different issues, so that we can keep this one to do with your issue of your ImagePolicy not working.

First of all, I understand your frustration with the jobs lying around if the Helm chart fails to install. The jobs are a workaround for a limitation with Helm on initial release, in that it wasn't able to create custom resource definitions. I've raised an issue to revisit those jobs (#41), because it might be possible to properly integrate them into the chart.

I thought we created the ibm-system namespace as part of the chart, but evidently not. Serves us right for only testing on IKS! #42

As for your ImagePolicy issue, that looks like it should work. Please could you confirm that the ImagePolicy you created has the `apiVersion` field set correctly? I'd expect it to be right at the top of the yaml. It should be:
```yaml
apiVersion: securityenforcement.admission.cloud.ibm.com/v1beta1
```

For further debugging, Portieris's logs should help identify what's going on. If you have [stern](https://github.com/wercker/stern), you can run `stern portieris -n ibm-system` to get all the logs for the multiple Portieris instances. If not, it might be easier to scale the Portieris deployment to one instance so that you only need to do `kubectl logs` on one pod.

**Comment by wu105** [comment]
The image policy has the verion string.  Here are the full image policy, which has `disable_tofu: true` added added later but did not help either:

```
apiVersion: securityenforcement.admission.cloud.ibm.com/v1beta1
kind: ImagePolicy
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"securityenforcement.admission.cloud.ibm.com/v1beta1","kind":"ImagePolicy","metadata":{"annotations":{},"name":"test-image-policy","namespace":"default"},"spec":{"repositories":[{"name":"*","policy":{"trust":{"disable_tofu":true,"enabled":true}}}]}}
  clusterName: ""
  creationTimestamp: 2018-12-01T05:58:39Z
  name: test-image-policy
  namespace: default
  resourceVersion: "25713101"
  selfLink: /apis/securityenforcement.admission.cloud.ibm.com/v1beta1/namespaces/default/imagepolicies/test-image-policy
  uid: 266a3ff7-f52e-11e8-9891-fa163eb8d59c
spec:
  repositories:
  - name: '*'
    policy:
      trust:
        disable_tofu: true
        enabled: true
```

The portieris pod logs are all empty, containing only something like  `I1201 05:34:44.599868       1 webhook.go:109] Starting notary Webhook on port 8000...`

**Comment by molepigeon** [comment]
Since you've got no messages about having received a request in the logs, I suspect that your admission webhook isn't working. Please could you print the result of:
```bash
kubectl get MutatingWebhookConfiguration image-admission-config -o yaml
```

Make sure to redact the `caBundle` field.

**Comment by wu105** [comment]
Here is the image-addmission-config:
```
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"admissionregistration.k8s.io/v1beta1","kind":"MutatingWebhookConfiguration","metadata":{"annotations":{},"labels":{"app":"portieris","chart":"portieris-0.2.0","heritage":"Tiller","release":"portieris"},"name":"image-admission-config","namespace":""},"webhooks":[{"clientConfig":{"caBundle":"LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNyRENDQVpRQ0NRQzFBU2FwMWl0NTBEQU5CZ2txaGtpRzl3MEJBUXNGQURBWE1SVXdFd1lEVlFRRERBeHcKYjNKMGFXVnlhWE5mWTJFd0lCY05NVGd3TkRJeU1UTXlOak01V2hnUE1qSTVNakF5TURVeE16STJNemxhTUJjeApGVEFUQmdOVkJBTU1ESEJ2Y25ScFpYSnBjMTlqWVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDCkFRb0NnZ0VCQU9JNitUVlYxZHlKNVlqbk9VZjNlKzlRd0wyMWEvSHlyNCtZdTBuZUhKMFViaGNHa3VLa0NudXQKUTBVNWVic2YvY1VNT2ZYVzVsMXlReTgyM3Fad0M5czdZWlZzdjd5R0dKSnVXTEhiRW82R2x0eDR3Mm9uMkdtbgpJVDJrTEZNaHRLTGh4anM4RjBzU1V3Zm5nQ3FLVFRZZ1l4OTNOVGM2WlFYZlNpenBpNDNqSTdLQWtkZWlDUEJwCkhzMVJ2ei9mVys1TUw4OTMwajRqL1RqVWNnTnk2cHlsbEdtYVdPemcxbkYrcjYyVDZuRzZNSkxMWlRLNWFhOC8KOUVBWlhRczdYOUJURmlLeSt4TjBCVlk5TWZKNDJNY3A3NndzT21mR29TUm9JbGxBRWtNaGRwRkZvTGR0YWp2agp5OW1DVTVFZHB3VUY1RkZtOHk2a0FZWFpRYmhteElrQ0F3RUFBVEFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBCjJSYkpqYTNUSzBlRjRLUUw5T2hNTHVVYkFZNzc1WFBTT3VXMkVjR05XRUs1OXA1UG1VdjhzeWplcEUwM2dYZ0EKSkxINENQcE1POGt4VStmdCtwTjFaRmNwT1NmSnFuMkx6WU95eTBQVjVtM3NPWEpzRHVWUGRXWmN4VUZVWGtqYgp4QjU4NVZURTRiSU1nT1Vyc3I3eVoraHU0SFlzRFBzeXZNbHBHcDQrSDBBOU9HZmwwaXVGL1BjTG5keVdWV0NPCkI5Z3dYMUdlNEdGbms3cWJGdUplVWwwN3BoL3VnOE5xTTdVOC9HcG1uMlVrbFNtTlRhd09kQW9kR2VUSTlCaTUKQmNyaWpVVERhRVhlNHhvTTNTR3NIaFVUTUhOTk9XdzMyR0tzeGEyZU1YL0RrdXhWN1pTYktLdUQvU1RhWkdFNgpIcDFBY2thajl5eDE1YWYzL0hldnlnPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=","service":{"name":"portieris","namespace":"ibm-system","path":"/admit"}},"failurePolicy":"Fail","name":"trust.hooks.securityenforcement.admission.cloud.ibm.com","rules":[{"apiGroups":["*"],"apiVersions":["*"],"operations":["CREATE","UPDATE"],"resources":["pods","deployments","replicationcontrollers","replicasets","daemonsets","statefulsets","jobs","cronjobs"]}]}]}
  creationTimestamp: 2018-12-01T05:35:00Z
  generation: 1
  labels:
    app: portieris
    chart: portieris-0.2.0
    heritage: Tiller
    release: portieris
  name: image-admission-config
  resourceVersion: "25711031"
  selfLink: /apis/admissionregistration.k8s.io/v1beta1/mutatingwebhookconfigurations/image-admission-config
  uid: d8b2b2b6-f52a-11e8-9891-fa163eb8d59c
webhooks:
- clientConfig:
    caBundle: ...redacted...
    service:
      name: portieris
      namespace: ibm-system
      path: /admit
  failurePolicy: Fail
  name: trust.hooks.securityenforcement.admission.cloud.ibm.com
  namespaceSelector: {}
  rules:
  - apiGroups:
    - '*'
    apiVersions:
    - '*'
    operations:
    - CREATE
    - UPDATE
    resources:
    - pods
    - deployments
    - replicationcontrollers
    - replicasets
    - daemonsets
    - statefulsets
    - jobs
    - cronjobs
```

**Comment by liamawhite** [comment]
Have you got any other mutating admission controllers running? It may be that your Kubernetes API server isn't configured to call them. https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#is-there-a-recommended-set-of-admission-controllers-to-use

**Comment by wu105** [comment]
Thanks for the information.  We are using k8s 1.9.1, and the apiserver had the following parameter (default):
`--admission-control=Initializers,NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,DefaultTolerationSeconds,NodeRestriction,ResourceQuota`
I replaced it in the /etc/kubernetes/manifests/kube-apiserver.yaml with the following according to the above document:
`--admission-control=NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,DefaultTolerationSeconds,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota`
The net change seems to replace `Initializers` and `NodeRestriction` with `MutatingAdmissionWebhook` and `ValidatingAdmissionWebhook`.
After deleted the apiserver pod and verified that the restarted apiserver had the intended parameter, an new problem developed: k8s could not find the image pulling secret when starting a pod until I changed the image policy to disable trust.

The error message when creating a pod (with minor obfuscations):
```
Error from server (InternalError): error when creating "pod-signed.yaml": Internal error occurred: admission webhook "trust.hooks.securityenforcement.admission.cloud.ibm.com" denied the request: 
Deny "core.harbor.domain.com/library/alpine:3.6", no valid ImagePullSecret defined for core.harbor.domain.com
```
The above error would go away after I added the following image policy:
```
cat <<EOF | kubectl apply -f -
apiVersion: securityenforcement.admission.cloud.ibm.com/v1beta1
kind: ImagePolicy
metadata:
  name: open-image-policy
  namespace: default
spec:
   repositories:
    - name: "core.harbor.domain.com/*/*"
      policy:
        trust:
          enabled: false
EOF
```
In  a portieris pod log, I found the following errors:
```
E1208 01:10:31.454882       1 oauth.go:73] Error sending request to registry-oauth: Post https://core.harbor.domain.com/oauth/token: x509: certificate signed by unknown authority
E1208 01:10:31.454916       1 controller.go:139] Post https://core.harbor.domain.com/oauth/token: x509: certificate signed by unknown authority
```
Our registry is using basic authentication, and the k8s cluster is otherwise configured to work with it ok when trust is disabled, i.e., no x509 certificate issue, and can use the existing image pulling secret.

Before adding the `open-image-policy` described above, the default cluster image policy was in effect.  Creating an image policy with the proper trustServer did not help:
```
cat <<EOF | kubectl apply -f -
apiVersion: securityenforcement.admission.cloud.ibm.com/v1beta1
kind: ImagePolicy
metadata:
  name: private-image-policy
  namespace: default
spec:
   repositories:
    - name: "core.harbor.domaiin.com/*/*"
      policy:
        trust:
          enabled: true
          trustServer: "https://notary.harbor.domain.com"
EOF
```

**Comment by molepigeon** [comment]
I think you need to put Harbor's CA into the Portieris container's trusted CAs.

**Comment by liamawhite** [comment]
I think @molepigeon is correct. The Notary client requires TLS and certs signed by a trusted CA. We added a feature in 0.5.1 that allows you to mount the Harbour CA's cert as part of the Kube secret as well. See https://github.com/IBM/portieris/blob/master/cmd/trust/main.go#L38.

```
apiVersion: v1
kind: Secret
metadata:
  name: portieris-certs
  namespace: ibm-system
type: Opaque
data:
  serverCert.pem: {{ .Files.Get "certs/serverCert.pem" | b64enc }}
  serverKey.pem: {{ .Files.Get "certs/serverKey.pem" | b64enc }}
  ca.pem: <base64-encodeed-harbor-self-signed-CA>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portieris
  namespace: ibm-system
  labels:
    app: portieris
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portieris
  template:
    metadata:
      labels:
        app: portieris
    spec:
      serviceAccountName: portieris
      containers:
        - name: portieris
          image: "docker.io/ibmcom/portieris:0.5.1"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
          - name: portieris-certs
            readOnly: true
            mountPath: "/etc/certs"                    
      volumes:
      - name: portieris-certs
        secret:
          secretName: portieris-certs
```

**Comment by liamawhite** [comment]
These are used by Portieris to communicate with Kube API server, they should be generated using [this](https://github.com/IBM/portieris/blob/master/helm/portieris/gencerts) script. They will be automatically populated by helm if you run that script.

If you're just playing around you won't need to generate your own certs, but these certs are in GitHub so don't use them in production!

**Comment by wu105** [comment]
After adding the ca.pem, I got the same errors.   I tried to override only the /etc/certs/ca.pem, but seems to hit a k8s bug.  Whatelse is supposed to be in /etc/certs?  cmd/trust/certs.go seems to suggest there are at least two more files.  It might be worth trying to create a full /etc/certs then mount to the pods.  

Here are the details. 
1.  I used the gencerts.sh to generate the serverCert and serverKey files, and supplied the ca file, added the secret to the deployment file, then updated its volumes, and the following is the result as printed by helm with the --debug parameter:
```
# Source: portieris/templates/deployment.yaml
### Secret and related volume added per https://github.com/IBM/portieris/issues/40
### deployment/upgrade process
### need yq
### sudo pip install  --trusted-host pypi.org --trusted-host files.pythonhosted.org --upgrade pip
### sudo pip install  --trusted-host pypi.org --trusted-host files.pythonhosted.org yq
### setup env for running helm, especially, define env KUBECONFIG
### cd .../portieris/helm
### ./gencerts.sh
### cleanpem.sh .../the.ca # the.ca is the root ca cert used by our notary, this step strips comments
### cp .../the.ca.pm certs/harborca.pem
### mv certs portieris
### helm upgrade portieris helm/portieris
apiVersion: v1
kind: Secret
metadata:
  name: portieris-certs
  namespace: ibm-system
type: Opaque
data:
  serverCert.pem: ...
  serverKey.pem: ...
  ca.pem: ...
---
# Source: portieris/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portieris
  namespace: ibm-system
  labels:
    app: portieris
    chart: portieris-0.2.0
    release: portieris
    heritage: Tiller
spec:
  replicas: 3
  selector:
    matchLabels:
      app: portieris
      release: portieris
  template:
    metadata:
      labels:
        app: portieris
        release: portieris
    spec:
      serviceAccountName: portieris
      volumes:
      - name: portieris-certs
        secret:
          secretName: portieris-certs
      containers:
        - name: portieris
          image: "docker.io/ibmcom/portieris:0.4.0"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
          volumeMounts:
          - name: portieris-certs
            readOnly: true
            mountPath: "/etc/certs"                    
          resources:
            {}
```

2. after getting the same error with the above update, tried to override only /etc/certs/ca.pem:
```
# Source: portieris/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portieris
  namespace: ibm-system
  labels:
    app: portieris
    chart: portieris-0.2.0
    release: portieris
    heritage: Tiller
spec:
  replicas: 3
  selector:
    matchLabels:
      app: portieris
      release: portieris
  template:
    metadata:
      labels:
        app: portieris
        release: portieris
    spec:
      serviceAccountName: portieris
      volumes:
      - name: portieris-certs
        secret:
          secretName: portieris-certs
      containers:
        - name: portieris
          image: "docker.io/ibmcom/portieris:0.4.0"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
          volumeMounts:
          - name: portieris-certs
            readOnly: true
            mountPath: "/etc/certs/ca.pem"
            subPath: "ca.pem"
          resources:
            {}
```
the portieris pod wont start, with the following errors (from kubectl describe pod), might be related to https://github.com/kubernetes/kubernetes/issues/61563:
```
Warning  Failed                 <invalid> (x8 over <invalid>)  kubelet, sladovmap67  Error: failed to prepare subPath for volumeMount "portieris-certs" of container "portieris"
```

**Comment by liamawhite** [comment]
You need to use the most recent charts with Portieris 0.5.1.

**Comment by wu105** [comment]
I seems to get the same error.   At the command line:
```
kubectl create -f .../kube/yaml/pod-signedalpine.yaml
Error from server (InternalError): error when creating ".../kube/yaml/pod-signedalpine.yaml": Internal error occurred: admission webhook "trust.hooks.securityenforcement.admission.cloud.ibm.com" denied the request: 
Deny "core.harbor.domain.com/library/alpine:3.6", no valid ImagePullSecret defined for core.harbor.domain.com
```
 in the portieris log:
```
I1215 03:05:53.138338       1 controller.go:65] Processing Trust Admission Request for CREATE on 
I1215 03:05:53.143057       1 controller.go:109] Container Image: core.harbor.domain.com/library/alpine:3.6   Namespace: default
I1215 03:05:53.156502       1 controller.go:119] Trust is enforced
E1215 03:05:53.388337       1 oauth.go:73] Error sending request to registry-oauth: Post https://core.harbor.domain.com/oauth/token: x509: certificate signed by unknown authority
E1215 03:05:53.388563       1 controller.go:139] Post https://core.harbor.domain.com/oauth/token: x509: certificate signed by unknown authority
```
we are interacting with the latest Harbor registry deployed today, master branch.
portieris was deployed using the latest master branch a moment ago with the following modifications:
1. Added harborca.pem to helm/portieris/certs/
2. verified using openssl that the certs presented by https://core.harbor.avaya.com/ and helm/portieris/certs/harborca.pem form a good certificate chain of three certificates.  Is there a command that we can run in the portieris pod to print out its /etc/certs/ca.pem?
3. helm/portieris/templates/secret.yaml reads like the  following (adding last line):
```
apiVersion: v1
kind: Secret
metadata:
  name: portieris-certs
  namespace: ibm-system
type: Opaque
data:
  serverCert.pem: {{ .Files.Get "certs/serverCert.pem" | b64enc }}
  serverKey.pem: {{ .Files.Get "certs/serverKey.pem" | b64enc }}
  ca.pem: {{ .Files.Get "certs/harborca.pem" | b64enc }}
```
4. helm/portieris/templates/deployment.yaml reads like the following (kept our comments at the  beginning but otherwise should be the same as the current master version):
```
---
### Secret and related volume added per https://github.com/IBM/portieris/issues/40
### deployment/upgrade process
### need yq
### sudo pip install  --trusted-host pypi.org --trusted-host files.pythonhosted.org --upgrade pip
### sudo pip install  --trusted-host pypi.org --trusted-host files.pythonhosted.org yq
### setup env for running helm, especially, define env KUBECONFIG
### cd .../portieris/helm
### ./gencerts.sh
### cleanpem.sh /app/pwu/certs/snodes.ca
### cp /app/pwu/certs/snodes.ca.pm certs/harborca.pem
### mv certs portieris
### helm upgrade portieris helm/portieris
### Secret portieris-certs in 0.5.1 is defined in secret.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "portieris.fullname" . }}
  namespace: ibm-system
  labels:
    app: {{ template "portieris.name" . }}
    chart: {{ template "portieris.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "portieris.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "portieris.name" . }}
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: portieris
      volumes:
      - name: portieris-certs
        secret:
          secretName: portieris-certs
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.host }}/{{ .Values.image.image }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
          - name: portieris-certs
            readOnly: true
            mountPath: "/etc/certs"
          env:
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      volumes:
      - name: portieris-certs
        secret:
          secretName: portieris-certs
```
