### ISSUE TITLE
Proivide a policy syntax to configure signature storage.

### ISSUE THREAD

**Issue by sjhx** [IBM/portieris#93]
If the registry used does not have support the simple signing registry extension then the signatures will need to be pulled from another store. 
Portieris does not support host configuration files.

**Comment by sjhx** [comment]
We need to be able to do the equivalent of installing a file in `/etc/containers/registries.d` similar to: 
```yaml
docker:
  target-registry-domain.com:
    sigstore: https://$USER:@SECRET@associated-with-target.com/folder/or-other
```
